<?php
session_start();
if(isset($_SESSION["logunamenew"])){
    unset($_SESSION["logunamenew"]);
    session_destroy();
    setcookie("logunamenew","",time()-3600000,"/");
}
header("Location:index.php");
exit;
?>